name: crud_between_screen
description: A sample project to verify CRUD between screens with listview.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  hooks_riverpod: ^1.0.3
  provider: ^6.0.2
  flutter_riverpod: ^1.0.3
  cupertino_icons: ^1.0.2
  freezed: ^2.0.3
  freezed_annotation: ^2.0.3
  shared_preferences: ^2.0.15
  json_annotation: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.2.0
  flutter_lints: ^1.0.0

  build_runner: ^2.1.10
flutter:

  uses-material-design: true